### ISSUE TITLE
Can't return numbers over 1000

### ISSUE THREAD

**Issue by jjspetz** [andy-richardson/github-yearly-contributions#1]
any number about a thousand returns only the first 3 digits. Example 1,006 returns 006

**Comment by andyrichardson** [comment]
Thanks for letting me know. 

I wasn't aware that commas would be inserted into the number and have ensured that this is now amended (commit 976cdf1d1de36e890c461a3a512182ee3b077917).

**Comment by jjspetz** [comment]
Nice, will you update the npm as well? I was using your npm for a project when i noticed the bug?

**Comment by jjspetz** [comment]
never mind the website is just slow
